name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        config:
        - os: 'ubuntu-24.04'
          cc: 'gcc-14'
          cxx: 'g++-14'
        #  prereq: |
        #    sudo apt install libstdc++-14-dev g++-14 gcc-14
        #- os: 'macos-14'
        #  cc: 'clang'
        #  cxx: 'clang++'
        #  prereq: |
        #    sudo xcode-select -s '/Applications/Xcode_15.2.app/Contents/Developer'

    runs-on: ${{ matrix.config.os }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: install prerequisites
      run: |
        ${{ matrix.config.prereq }}
    - name: configure
      run: |
        ${{ matrix.config.cxx }} --version
        ./scripts/fix-timestamps.sh
        mkdir objdir
        cd objdir
        ../configure CC='${{ matrix.config.cc }}' CXX='${{ matrix.config.cxx }}' --enable-shared --enable-unit-tests --with-working-locale
    - name: make
      run: cd objdir ; make
    - name: make check
      run: cd objdir ; make check
